Feature
vitali-usik/apollo pull request #2
Opened 2018-10-31 11:02 UTC by EllaUsik

<header> is done

2018-11-13 11:51 UTC, vitali-usik requested changes
Картинка `images/womanphoto.png` весит `1.14MB` весит слишком много. Используй https://compressor.io/compress для сжатия. Есть мелкие недочеты. Остальное в целом хорошо, молодец!

2018-11-13 11:51 UTC, vitali-usik commented on index.html
> +      <header class="block">
`header` можно использовать как селектор, ему не нужен класс. Подразумевается что `header` только один на странице

2018-11-13 11:51 UTC, vitali-usik commented on index.html
> +          <span class="title-part2">
`title-part1` и `title-part2` содержат одинаковые стили, но первый блок добавляет "жирность" тексту. Поэтому можно что бы класс был title, но Apollo обернуть в тег <b> или добавить ему класс модификатор `title-bold`

2018-11-13 11:51 UTC, vitali-usik commented on index.html
> +              <span class="about-title-part2">
Аналогично комментарию выше

2018-11-13 11:51 UTC, vitali-usik commented on index.html
> +          <span class="say-hallo-title2">Hello</span>
Аналогично комментарию выше

2018-11-13 11:51 UTC, vitali-usik commented on index.html
> +          </span>
Аналогично комментарию выше

2018-11-13 11:51 UTC, vitali-usik commented on index.html
> +            <input class="your-email" value="Your Email"></input>
Не `value`, а `placeholder`

2018-11-13 11:51 UTC, vitali-usik commented on index.html
> +            <input class="subcject" value="Subcject"></input>
Не `value`, а `placeholder`

2018-11-13 11:51 UTC, vitali-usik commented on index.html
> +            <textarea class="message">Message</textarea>
`placeholder`

2018-11-19 10:24 UTC, EllaUsik commented on index.html
> +      <header class="block">
Хорошо. А если каждый блок у меня, по мимо оригинального названия и соответствующих им свойствам, имеет некоторые общие свойства, которые описываются в общем для всех классе "block", то в header его убрать и через запятую от  block писать header?

2018-11-19 11:04 UTC, EllaUsik commented
поправила

2018-11-22 13:35 UTC, vitali-usik commented on index.html
> +      <header class="block">
Тогда можно

2018-11-22 13:35 UTC, merged